name: centernet-workflow
on:
  push:
    branches:
      - master
      - feature/**
    paths:
      - centernet/**
      - .github/**
      - tests.py
  pull_request:
    branches:
      - master
    paths:
      - centernet/**
      - .github/**
      - tests.py
jobs:
  build-using-cmake-on-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sh install.sh
          mkdir data && cd data
          wget https://github.com/soumik12345/centernet/releases/download/0.1/pku-autonomous-driving.zip
          unzip -q pku-autonomous-driving.zip
          rm pku-autonomous-driving.zip && cd ..
          source venv/bin/activate
          pytest tests.py -s
          deactivate
